#!/usr/bin/perl
use strict;
use warnings;
use File::Basename;
use File::Find;
use File::Spec;
use Getopt::Long;

my $forced_syntax;
my $check_supported;
my $output_html;
my $output_svg;
GetOptions(
    "syntax|s=s" => \$forced_syntax,
    "supported"  => \$check_supported,
    "html"       => \$output_html,
    "svg"        => \$output_svg,
) or die "Usage: $0 [-s syntax] [--supported] [--html|--svg] [file] [nanorc_dir]\n";

my $target_file = shift @ARGV;
my $nanorc_dir  = shift @ARGV // $ENV{NANOCOLOUR_DIR};

if (!$nanorc_dir || (!-d $nanorc_dir && !-f $nanorc_dir)) {
    die "Usage: $0 [-s syntax] [--supported] [--html|--svg] [file] [nanorc_dir]\n(Set NANOCOLOUR_DIR or provide a valid nanorc_dir or nanorc file)\n";
}

if (!$target_file && !$forced_syntax && !$check_supported) {
    die "Usage: $0 [-s syntax] [--supported] [--html|--svg] [file] [nanorc_dir]\n";
}

if ($output_html && $output_svg) {
    die "Only one of --html or --svg may be specified\n";
}

my %color_map = (
    black   => 0,
    red     => 1,
    green   => 2,
    yellow  => 3,
    blue    => 4,
    magenta => 5,
    cyan    => 6,
    white   => 7,
    normal  => 9,
);

my %html_color_map = (
    black         => '#000000',
    red           => '#800000',
    green         => '#008000',
    yellow        => '#808000',
    blue          => '#000080',
    magenta       => '#800080',
    cyan          => '#008080',
    white         => '#c0c0c0',
    brightblack   => '#808080',
    brightred     => '#ff0000',
    brightgreen   => '#00ff00',
    brightyellow  => '#ffff00',
    brightblue    => '#0000ff',
    brightmagenta => '#ff00ff',
    brightcyan    => '#00ffff',
    brightwhite   => '#ffffff',
    normal        => 'inherit',
);

my %style_defs;

sub get_ansi {
    my ($fg, $bg) = @_;
    my $ansi = "\e[0m";
    return $ansi unless (defined $fg && $fg ne "") || (defined $bg && $bg ne "");
    
    if (defined $fg && $fg ne "") {
        my $bright = 0;
        if ($fg =~ s/^bright//i) {
            $bright = 1;
        }
        
        my $fg_code = $color_map{lc($fg)};
        if (defined $fg_code) {
            $ansi .= "\e[" . ($bright ? "1;" : "") . (30 + $fg_code) . "m";
        }
    }
    
    if (defined $bg && $bg ne "") {
        my $bg_code = $color_map{lc($bg)};
        if (defined $bg_code) {
            $ansi .= "\e[" . (40 + $bg_code) . "m";
        }
    }
    return $ansi;
}

sub sanitise_name {
    my ($name) = @_;
    $name = lc($name // "");
    $name =~ s/[^a-z0-9]+/-/g;
    $name =~ s/^-+//;
    $name =~ s/-+$//;
    return $name ne "" ? $name : "plain";
}

sub get_style_key {
    my ($fg, $bg) = @_;
    my $norm_fg = defined($fg) ? lc($fg) : "";
    my $norm_bg = defined($bg) ? lc($bg) : "";
    return "fg=$norm_fg;bg=$norm_bg";
}

sub register_style {
    my ($fg, $bg) = @_;
    my $style_key = get_style_key($fg, $bg);
    return $style_defs{$style_key} if exists $style_defs{$style_key};

    my @classes;
    my %style = (
        key     => $style_key,
        fg      => defined($fg) ? lc($fg) : "",
        bg      => defined($bg) ? lc($bg) : "",
        ansi    => get_ansi($fg, $bg),
        classes => "",
    );

    if (defined $fg && $fg ne "") {
        push @classes, "nanocolour-fg-" . sanitise_name($fg);
    }
    if (defined $bg && $bg ne "") {
        push @classes, "nanocolour-bg-" . sanitise_name($bg);
    }

    $style{classes} = join(" ", @classes);
    $style_defs{$style_key} = \%style;
    return \%style;
}

sub html_escape {
    my ($text) = @_;
    $text =~ s/&/&amp;/g;
    $text =~ s/</&lt;/g;
    $text =~ s/>/&gt;/g;
    $text =~ s/"/&quot;/g;
    $text =~ s/'/&#39;/g;
    return $text;
}

sub svg_escape {
    my ($text) = @_;
    return html_escape($text);
}

sub emit_css_block {
    my ($fh, $selector_prefix) = @_;
    my @colours = grep { $_ ne 'normal' } sort keys %html_color_map;

    print $fh "${selector_prefix}.nanocolour { white-space: pre; font-family: monospace; }\n";
    foreach my $colour (@colours) {
        my $css_name = sanitise_name($colour);
        my $value = $html_color_map{$colour};
        print $fh "${selector_prefix}.nanocolour-fg-$css_name { color: $value; fill: $value; }\n";
        print $fh "${selector_prefix}.nanocolour-bg-$css_name { background-color: $value; }\n";
        print $fh "${selector_prefix}rect.nanocolour-bg-$css_name { fill: $value; }\n";
    }
    print $fh "${selector_prefix}.nanocolour-fg-normal { color: inherit; fill: currentColor; }\n";
    print $fh "${selector_prefix}.nanocolour-bg-normal { background-color: transparent; }\n";
    print $fh "${selector_prefix}rect.nanocolour-bg-normal { fill: none; }\n";
}

my @syntax_list;
my %syntaxes;
my $active_syntax;
my %seen_rc;

# Confirm a rule's regex actually compiles, reporting the offending nanorc
# file, line and rule text rather than letting a malformed pattern fail
# later with a confusing error pointing at this script's own source line.
# Returns true if the regex is usable. A bad rule is reported and skipped
# (rather than aborting the whole run), so one broken syntax definition
# elsewhere in the nanorc directory does not stop unrelated files being
# coloured.
sub validate_regex {
    my ($re, $rc_file, $line_no, $raw_line) = @_;
    eval { qr/($re)/ };
    return 1 unless $@;

    my $err = $@;
    $err =~ s/ at \S+ line \d+\.?\s*$//s;
    chomp $raw_line;
    $raw_line =~ s/^\s+|\s+$//g;
    warn "nano-colour: invalid regular expression in $rc_file, line $line_no - rule skipped:\n" .
         "  $raw_line\n" .
         "  Pattern: $re\n" .
         "  $err\n";
    return 0;
}

sub parse_nanorc {
    my ($rc_file) = @_;
    $rc_file = File::Spec->rel2abs($rc_file);
    return if $seen_rc{$rc_file}++;
    
    open(my $fh, "<", $rc_file) or return;
    my $dir = dirname($rc_file);
    
    while (<$fh>) {
        next if /^\s*#/;
        if (/^\s*include\s+["']?([^"'\s]+)["']?/) {
            my $inc_pattern = $1;
            $inc_pattern =~ s|^~|$ENV{HOME}|;
            if (!File::Spec->file_name_is_absolute($inc_pattern)) {
                $inc_pattern = File::Spec->catfile($dir, $inc_pattern);
            }
            foreach my $inc_file (glob($inc_pattern)) {
                parse_nanorc($inc_file);
            }
        } elsif (/^\s*syntax\s+["']?([^"'\s]+)["']?\s*(.*)/) {
            my $name = $1;
            my $ext_str = $2;
            $active_syntax = { name => $name, extensions => [], headers => [], rules => [] };
            push @syntax_list, $active_syntax;
            while ($ext_str =~ /"((?:[^"\\]|\\.)*)"|(\S+)/g) {
                push @{$active_syntax->{extensions}}, $1 // $2;
            }
        } elsif (/^\s*header\s+(.*)/ && $active_syntax) {
            my $header_str = $1;
            while ($header_str =~ /"((?:[^"\\]|\\.)*)"|(\S+)/g) {
                push @{$active_syntax->{headers}}, $1 // $2;
            }
        } elsif (/^\s*(icolor|color)\s+([a-z,]+)\s+(.*)/i && $active_syntax) {
            my $icase = (lc($1) eq 'icolor');
            my $colors = $2;
            my $rest = $3;
            
            my ($fg, $bg) = split(/,/, $colors);
            $bg = "" unless defined $bg;
            my $style = register_style($fg, $bg);
            
            if ($rest =~ /^start="((?:[^"\\]|\\.)*)"\s+end="((?:[^"\\]|\\.)*)"/) {
                my ($s, $e) = ($1, $2);
                $s =~ s/\\</\\b/g; $s =~ s/\\>/\\b/g;
                $e =~ s/\\</\\b/g; $e =~ s/\\>/\\b/g;
                if (validate_regex($s, $rc_file, $., $_) && validate_regex($e, $rc_file, $., $_)) {
                    push @{$active_syntax->{rules}}, { type => 'multi', start => $s, end => $e, style_key => $style->{key}, icase => $icase };
                }
            } elsif ($rest =~ /\bstart=/ && $rest =~ /\bend=/) {
                # Looks like a start=/end= rule, but didn't match the strict
                # form above (e.g. an unescaped double quote embedded in the
                # pattern). Report this clearly and skip it, rather than
                # silently falling through to the single-line tokeniser
                # below, which would mangle it into one or more bogus
                # patterns that could fail confusingly much later.
                my $raw_line = $_;
                chomp $raw_line;
                $raw_line =~ s/^\s+|\s+$//g;
                warn "nano-colour: malformed start=/end= rule in $rc_file, line $. - rule skipped:\n" .
                     "  $raw_line\n" .
                     "  (embedded double quotes in the pattern must be backslash-escaped, e.g. \\\")\n";
            } else {
                my @raw = split(/(\s+)/, $rest);
                while (@raw) {
                    my $p = shift @raw;
                    next if $p =~ /^\s*$/;
                    if ($p =~ /^"/ && ($p !~ /[^\\]"$/ || $p eq '"')) {
                        while (@raw) {
                            $p .= shift @raw;
                            last if $p =~ /[^\\]"$/;
                        }
                    }
                    $p =~ s/^"//;
                    $p =~ s/"$//;
                    next if $p eq "";
                    $p =~ s/\\</\\b/g; $p =~ s/\\>/\\b/g;
                    next unless validate_regex($p, $rc_file, $., $_);
                    push @{$active_syntax->{rules}}, { type => 'single', re => $p, style_key => $style->{key}, icase => $icase };
                }
            }
        }
    }
    close($fh);
}

# Collect initial files
my @initial_rc_files;
if (-f $nanorc_dir) {
    push @initial_rc_files, $nanorc_dir;
} elsif (-d $nanorc_dir) {
    find({
        wanted => sub {
            push @initial_rc_files, $File::Find::name if /\.nanorc$/ || $_ eq 'nanorc';
        },
        no_chdir => 1,
    }, $nanorc_dir);
    @initial_rc_files = sort @initial_rc_files;
}

foreach my $rc_file (@initial_rc_files) {
    parse_nanorc($rc_file);
}

my $selected_syntax;
my $target_path = $target_file // "";
my $first_line = "";
if ($target_file && $target_file ne '-') {
    if (open(my $tfh, "<", $target_file)) {
        $first_line = <$tfh> // "";
        close($tfh);
    }
}

if ($forced_syntax) {
    ($selected_syntax) = grep { $_->{name} eq $forced_syntax } @syntax_list;
} else {
    if ($target_path) {
        foreach my $s (@syntax_list) {
            foreach my $ext_re (@{$s->{extensions}}) {
                my $re = $ext_re;
                $re =~ s/\\</\\b/g;
                $re =~ s/\\>/\\b/g;
                if ($target_path =~ /$re/) {
                    $selected_syntax = $s;
                    last;
                }
            }
            last if $selected_syntax;
        }
    }
    if (!$selected_syntax && $first_line) {
        foreach my $s (@syntax_list) {
            foreach my $header_re (@{$s->{headers}}) {
                my $re = $header_re;
                $re =~ s/\\</\\b/g;
                $re =~ s/\\>/\\b/g;
                if ($first_line =~ /$re/) {
                    $selected_syntax = $s;
                    last;
                }
            }
            last if $selected_syntax;
        }
    }
}

if ($check_supported) {
    if ($selected_syntax) {
        print "$selected_syntax->{name}\n";
        exit 0;
    } else {
        exit 1;
    }
}

my $in_fh;
if ($target_file && $target_file ne '-') {
    open($in_fh, "<", $target_file) or die "Cannot open $target_file: $!";
} else {
    $in_fh = \*STDIN;
}

my $default_style = register_style("", "");

if (!$selected_syntax) {
    my @plain_lines;
    while (my $line = <$in_fh>) {
        chomp $line;
        push @plain_lines, {
            length => length($line),
            runs   => [ { style_key => $default_style->{key}, text => $line } ],
        };
    }
    close($in_fh);

    if ($output_html) {
        print_html_output(\@plain_lines, "plain");
    } elsif ($output_svg) {
        print_svg_output(\@plain_lines, "plain");
    } else {
        foreach my $line (@plain_lines) {
            print $line->{runs}[0]{text}, "\n";
        }
    }
    exit 0;
}

# Use the pre-parsed rules
my @rules = @{$selected_syntax->{rules}};

sub paint_range {
    my ($char_styles, $start, $end, $style_key) = @_;
    return if $end <= $start;

    for (my $i = $start; $i < $end; $i++) {
        $char_styles->[$i] = $style_key;
    }
}

sub line_to_runs {
    my ($chars, $char_styles) = @_;
    my @runs;
    my $count = scalar(@{$chars});
    return [] if $count == 0;

    my $current_style = $char_styles->[0];
    my $buffer = "";

    for (my $i = 0; $i < $count; $i++) {
        if ($char_styles->[$i] ne $current_style) {
            push @runs, { style_key => $current_style, text => $buffer };
            $buffer = "";
            $current_style = $char_styles->[$i];
        }
        $buffer .= $chars->[$i];
    }

    push @runs, { style_key => $current_style, text => $buffer };
    return \@runs;
}

sub print_ansi_output {
    my ($lines) = @_;

    foreach my $line (@{$lines}) {
        my $last_ansi = "";
        foreach my $run (@{$line->{runs}}) {
            my $style = $style_defs{$run->{style_key}};
            if ($style->{ansi} ne $last_ansi) {
                print $style->{ansi};
                $last_ansi = $style->{ansi};
            }
            print $run->{text};
        }
        print "\e[0m\n";
    }
}

sub print_html_output {
    my ($lines, $syntax_name) = @_;
    my $syntax_class = "nanocolour-" . sanitise_name($syntax_name);

    print "<style>\n";
    emit_css_block(\*STDOUT, "");
    print "</style>\n";
    print "<div class='nanocolour $syntax_class'>\n";
    foreach my $line (@{$lines}) {
        foreach my $run (@{$line->{runs}}) {
            my $style = $style_defs{$run->{style_key}};
            my $text = html_escape($run->{text});
            if ($style->{classes} ne "") {
                print "<span class='$style->{classes}'>$text</span>";
            } else {
                print $text;
            }
        }
        print "\n";
    }
    print "</div>\n";
}

sub print_svg_output {
    my ($lines, $syntax_name) = @_;
    my $syntax_class = "nanocolour-" . sanitise_name($syntax_name);
    my $font_size = 14;
    my $char_width = 8;
    my $line_height = 18;
    my $margin = 8;
    my $line_count = scalar(@{$lines});
    my $max_columns = 0;

    foreach my $line (@{$lines}) {
        $max_columns = $line->{length} if $line->{length} > $max_columns;
    }

    my $width = ($max_columns * $char_width) + ($margin * 2);
    my $height = ($line_count * $line_height) + ($margin * 2);
    $width = $margin * 2 if $width < $margin * 2;
    $height = $margin * 2 if $height < $margin * 2;

    print "<svg xmlns='http://www.w3.org/2000/svg' class='nanocolour $syntax_class' width='$width' height='$height' viewBox='0 0 $width $height' font-family='monospace'>\n";
    print "<style>\n";
    emit_css_block(\*STDOUT, "svg ");
    print "</style>\n";

    for (my $line_index = 0; $line_index < $line_count; $line_index++) {
        my $line = $lines->[$line_index];
        my $y = $margin + (($line_index + 1) * $line_height) - 4;
        my $rect_y = $margin + ($line_index * $line_height);
        my $column = 0;

        foreach my $run (@{$line->{runs}}) {
            my $style = $style_defs{$run->{style_key}};
            my $run_length = length($run->{text});
            if ($style->{bg} ne "" && $style->{bg} ne "normal" && $run_length > 0) {
                my $x = $margin + ($column * $char_width);
                my $rect_width = $run_length * $char_width;
                print "<rect class='$style->{classes}' x='$x' y='$rect_y' width='$rect_width' height='$line_height' />";
            }
            $column += $run_length;
        }

        my $x = $margin;
        print "<text x='$x' y='$y' xml:space='preserve'>";
        foreach my $run (@{$line->{runs}}) {
            my $style = $style_defs{$run->{style_key}};
            my $text = svg_escape($run->{text});
            if ($style->{classes} ne "") {
                print "<tspan class='$style->{classes}'>$text</tspan>";
            } else {
                print $text;
            }
        }
        print "</text>\n";
    }

    print "</svg>\n";
}

# Process the target stream
my $current_multi_rule = undef;
my @rendered_lines;

while (my $line = <$in_fh>) {
    chomp $line;
    my @chars = split(//, $line);
    my @char_styles = (($default_style->{key}) x scalar(@chars));

    # Apply all syntax rules in order
    for (my $rule_index = 0; $rule_index <= $#rules; $rule_index++) {
        my $rule = $rules[$rule_index];
        my $icase = $rule->{icase};
        my $search_from = 0;

        if ($current_multi_rule && $current_multi_rule->{index} == $rule_index) {
            my $end_re = $rule->{end};

            if ($icase ? $line =~ /($end_re)/i : $line =~ /($end_re)/) {
                my $end_pos = $+[0];
                paint_range(\@char_styles, 0, $end_pos, $rule->{style_key});
                $current_multi_rule = undef;
                $search_from = $end_pos;
            } else {
                paint_range(\@char_styles, 0, scalar(@chars), $rule->{style_key});
                next;
            }
        }

        if ($rule->{type} eq 'single') {
            my $re = $rule->{re};
            pos($line) = $search_from;
            while ($icase ? $line =~ /($re)/gi : $line =~ /($re)/g) {
                my $start = $-[0];
                my $end = $+[0];
                paint_range(\@char_styles, $start, $end, $rule->{style_key});
                if ($start == $end) {
                    if (pos($line) < length($line)) {
                        pos($line) = pos($line) + 1;
                    } else {
                        last;
                    }
                }
            }
        } else {
            # Multiline rule start/end logic within this line
            my $start_re = $rule->{start};
            my $end_re = $rule->{end};
            
            pos($line) = $search_from;
            while ($icase ? $line =~ /($start_re)/gi : $line =~ /($start_re)/g) {
                my $start = $-[0];
                my $start_end = $+[0];
                
                # Rule starts here
                $current_multi_rule = { index => $rule_index, rule => $rule };
                
                # Look for end on the same line
                my $suffix = substr($line, $start_end);
                if ($icase ? $suffix =~ /($end_re)/i : $suffix =~ /($end_re)/) {
                    my $end_len = length($1);
                    my $end_pos_in_line = $start_end + $-[0] + $end_len;
                    paint_range(\@char_styles, $start, $end_pos_in_line, $rule->{style_key});
                    $current_multi_rule = undef;
                    pos($line) = ($end_pos_in_line > $start) ? $end_pos_in_line : $start + 1;
                } else {
                    paint_range(\@char_styles, $start, scalar(@chars), $rule->{style_key});
                    last; # Continues to next line
                }
            }
        }
    }

    push @rendered_lines, {
        length => scalar(@chars),
        runs   => line_to_runs(\@chars, \@char_styles),
    };
}
close($in_fh);

if ($output_html) {
    print_html_output(\@rendered_lines, $selected_syntax->{name});
} elsif ($output_svg) {
    print_svg_output(\@rendered_lines, $selected_syntax->{name});
} else {
    print_ansi_output(\@rendered_lines);
}
