#!/usr/bin/perl
use strict;
use warnings;
use File::Basename;
use File::Find;
use File::Spec;
use Getopt::Long;

my $forced_syntax;
my $check_supported;
GetOptions(
    "syntax|s=s" => \$forced_syntax,
    "supported"  => \$check_supported,
) or die "Usage: $0 [-s syntax] [--supported] [file] [nanorc_dir]\n";

my $target_file = shift @ARGV;
my $nanorc_dir  = shift @ARGV // $ENV{NANOCOLOUR_DIR};

if (!$nanorc_dir || (!-d $nanorc_dir && !-f $nanorc_dir)) {
    die "Usage: $0 [-s syntax] [--supported] [file] [nanorc_dir]\n(Set NANOCOLOUR_DIR or provide a valid nanorc_dir or nanorc file)\n";
}

if (!$target_file && !$forced_syntax && !$check_supported) {
    die "Usage: $0 [-s syntax] [--supported] [file] [nanorc_dir]\n";
}

my %color_map = (
    black   => 0,
    red     => 1,
    green   => 2,
    yellow  => 3,
    blue    => 4,
    magenta => 5,
    cyan    => 6,
    white   => 7,
    normal  => 9,
);

sub get_ansi {
    my ($fg, $bg) = @_;
    my $ansi = "\e[0m";
    return $ansi unless (defined $fg && $fg ne "") || (defined $bg && $bg ne "");
    
    if (defined $fg && $fg ne "") {
        my $bright = 0;
        if ($fg =~ s/^bright//i) {
            $bright = 1;
        }
        
        my $fg_code = $color_map{lc($fg)};
        if (defined $fg_code) {
            $ansi .= "\e[" . ($bright ? "1;" : "") . (30 + $fg_code) . "m";
        }
    }
    
    if (defined $bg && $bg ne "") {
        my $bg_code = $color_map{lc($bg)};
        if (defined $bg_code) {
            $ansi .= "\e[" . (40 + $bg_code) . "m";
        }
    }
    return $ansi;
}

my @syntax_list;
my %syntaxes;
my $active_syntax;
my %seen_rc;

sub parse_nanorc {
    my ($rc_file) = @_;
    $rc_file = File::Spec->rel2abs($rc_file);
    return if $seen_rc{$rc_file}++;
    
    open(my $fh, "<", $rc_file) or return;
    my $dir = dirname($rc_file);
    
    while (<$fh>) {
        next if /^\s*#/;
        if (/^\s*include\s+["']?([^"'\s]+)["']?/) {
            my $inc_pattern = $1;
            $inc_pattern =~ s|^~|$ENV{HOME}|;
            if (!File::Spec->file_name_is_absolute($inc_pattern)) {
                $inc_pattern = File::Spec->catfile($dir, $inc_pattern);
            }
            foreach my $inc_file (glob($inc_pattern)) {
                parse_nanorc($inc_file);
            }
        } elsif (/^\s*syntax\s+["']?([^"'\s]+)["']?\s*(.*)/) {
            my $name = $1;
            my $ext_str = $2;
            $active_syntax = { name => $name, extensions => [], headers => [], rules => [] };
            push @syntax_list, $active_syntax;
            while ($ext_str =~ /"((?:[^"\\]|\\.)*)"|(\S+)/g) {
                push @{$active_syntax->{extensions}}, $1 // $2;
            }
        } elsif (/^\s*header\s+(.*)/ && $active_syntax) {
            my $header_str = $1;
            while ($header_str =~ /"((?:[^"\\]|\\.)*)"|(\S+)/g) {
                push @{$active_syntax->{headers}}, $1 // $2;
            }
        } elsif (/^\s*(icolor|color)\s+([a-z,]+)\s+(.*)/i && $active_syntax) {
            my $icase = (lc($1) eq 'icolor');
            my $colors = $2;
            my $rest = $3;
            
            my ($fg, $bg) = split(/,/, $colors);
            $bg = "" unless defined $bg;
            my $ansi = get_ansi($fg, $bg);
            
            if ($rest =~ /^start="((?:[^"\\]|\\.)*)"\s+end="((?:[^"\\]|\\.)*)"/) {
                my ($s, $e) = ($1, $2);
                $s =~ s/\\</\\b/g; $s =~ s/\\>/\\b/g;
                $e =~ s/\\</\\b/g; $e =~ s/\\>/\\b/g;
                push @{$active_syntax->{rules}}, { type => 'multi', start => $s, end => $e, ansi => $ansi, icase => $icase };
            } else {
                my @raw = split(/(\s+)/, $rest);
                while (@raw) {
                    my $p = shift @raw;
                    next if $p =~ /^\s*$/;
                    if ($p =~ /^"/ && ($p !~ /[^\\]"$/ || $p eq '"')) {
                        while (@raw) {
                            $p .= shift @raw;
                            last if $p =~ /[^\\]"$/;
                        }
                    }
                    $p =~ s/^"//;
                    $p =~ s/"$//;
                    next if $p eq "";
                    $p =~ s/\\</\\b/g; $p =~ s/\\>/\\b/g;
                    push @{$active_syntax->{rules}}, { type => 'single', re => $p, ansi => $ansi, icase => $icase };
                }
            }
        }
    }
    close($fh);
}

# Collect initial files
my @initial_rc_files;
if (-f $nanorc_dir) {
    push @initial_rc_files, $nanorc_dir;
} elsif (-d $nanorc_dir) {
    find({
        wanted => sub {
            push @initial_rc_files, $File::Find::name if /\.nanorc$/ || $_ eq 'nanorc';
        },
        no_chdir => 1,
    }, $nanorc_dir);
    @initial_rc_files = sort @initial_rc_files;
}

foreach my $rc_file (@initial_rc_files) {
    parse_nanorc($rc_file);
}

my $selected_syntax;
my $target_path = $target_file // "";
my $first_line = "";
if ($target_file && $target_file ne '-') {
    if (open(my $tfh, "<", $target_file)) {
        $first_line = <$tfh> // "";
        close($tfh);
    }
}

if ($forced_syntax) {
    ($selected_syntax) = grep { $_->{name} eq $forced_syntax } @syntax_list;
} else {
    if ($target_path) {
        foreach my $s (@syntax_list) {
            foreach my $ext_re (@{$s->{extensions}}) {
                my $re = $ext_re;
                $re =~ s/\\</\\b/g;
                $re =~ s/\\>/\\b/g;
                if ($target_path =~ /$re/) {
                    $selected_syntax = $s;
                    last;
                }
            }
            last if $selected_syntax;
        }
    }
    if (!$selected_syntax && $first_line) {
        foreach my $s (@syntax_list) {
            foreach my $header_re (@{$s->{headers}}) {
                my $re = $header_re;
                $re =~ s/\\</\\b/g;
                $re =~ s/\\>/\\b/g;
                if ($first_line =~ /$re/) {
                    $selected_syntax = $s;
                    last;
                }
            }
            last if $selected_syntax;
        }
    }
}

if ($check_supported) {
    if ($selected_syntax) {
        print "$selected_syntax->{name}\n";
        exit 0;
    } else {
        exit 1;
    }
}

my $in_fh;
if ($target_file && $target_file ne '-') {
    open($in_fh, "<", $target_file) or die "Cannot open $target_file: $!";
} else {
    $in_fh = \*STDIN;
}

if (!$selected_syntax) {
    # Default to plain text
    print while <$in_fh>;
    close($in_fh);
    exit;
}

# Use the pre-parsed rules
my @rules = @{$selected_syntax->{rules}};

# Process the target stream
my $current_multi_rule = undef;

while (my $line = <$in_fh>) {
    chomp $line;
    my @chars = split(//, $line);
    my @char_ansi = ("\e[0m") x (scalar(@chars) + 1);
    
    # Apply multiline state from previous line if any
    if ($current_multi_rule) {
        my $re = $current_multi_rule->{end};
        my $icase = $current_multi_rule->{icase};
        for (my $i = 0; $i <= $#chars; $i++) { $char_ansi[$i] = $current_multi_rule->{ansi}; }
        
        if ($icase ? $line =~ /($re)/i : $line =~ /($re)/) {
            my $end_pos = $-[0] + length($1);
            for (my $i = $end_pos; $i <= $#chars; $i++) { $char_ansi[$i] = "\e[0m"; }
            $current_multi_rule = undef;
        }
    }
    
    # Apply all syntax rules in order
    foreach my $rule (@rules) {
        my $icase = $rule->{icase};
        if ($rule->{type} eq 'single') {
            my $re = $rule->{re};
            pos($line) = 0;
            while ($icase ? $line =~ /($re)/gi : $line =~ /($re)/g) {
                my $start = $-[0];
                my $end = $+[0];
                for (my $i = $start; $i < $end; $i++) {
                    $char_ansi[$i] = $rule->{ansi};
                }
                if ($start == $end) {
                    if (pos($line) < length($line)) {
                        pos($line) = pos($line) + 1;
                    } else {
                        last;
                    }
                }
            }
        } else {
            # Multiline rule start/end logic within this line
            my $start_re = $rule->{start};
            my $end_re = $rule->{end};
            
            pos($line) = 0;
            while ($icase ? $line =~ /($start_re)/gi : $line =~ /($start_re)/g) {
                my $start = $-[0];
                my $start_end = $+[0];
                
                # Rule starts here
                $current_multi_rule = $rule;
                for (my $i = $start; $i <= $#chars; $i++) { $char_ansi[$i] = $rule->{ansi}; }
                
                # Look for end on the same line
                my $suffix = substr($line, $start_end);
                if ($icase ? $suffix =~ /($end_re)/i : $suffix =~ /($end_re)/) {
                    my $end_len = length($1);
                    my $end_pos_in_line = $start_end + $-[0] + $end_len;
                    for (my $i = $end_pos_in_line; $i <= $#chars; $i++) { $char_ansi[$i] = "\e[0m"; }
                    $current_multi_rule = undef;
                    pos($line) = ($end_pos_in_line > $start) ? $end_pos_in_line : $start + 1;
                } else {
                    last; # Continues to next line
                }
            }
        }
    }
    
    # Print colored line
    my $last_ansi = "";
    for (my $i = 0; $i <= $#chars; $i++) {
        if ($char_ansi[$i] ne $last_ansi) {
            print $char_ansi[$i];
            $last_ansi = $char_ansi[$i];
        }
        print $chars[$i];
    }
    print "\e[0m\n";
}
close($in_fh);
